language: python
python:
    - 3.6
before_install:
    - sudo rm -f /etc/boto.cfg
install:
    - pip install boto3
    - pip install utils
    - pip install moto
    - pip install psycopg2
    - pip install coverage
    - pip install pytest
    - pip install pytest-env
    - pip install google_compute_engine
    - pip install xmljson
branches:
    only:
        - master
        - develop
        - SDC-1399
        - SDC-3960
addons:
    sonarcloud:
        organization: "kbrpurchase1"
script: 
    - coverage erase
    - coverage run -m pytest tests/
    - coverage xml -i
